import { User } from "../models/user";
import * as moment from "moment";
import { Guid } from "../helpers/Guid";

export const defaultUsers: Array<User> = [
  {
    id: Guid.newGuid(),
    firstname: "nicolas",
    lastname: "azzara",
    username: "nkonko",
    password: "123456test",
    email: "nkonko@hotmail.com",
    birthday: moment().subtract(29, "year"),
    role: "superadmin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "jonathan",
    lastname: "durante",
    username: "jonaDur",
    password: "123456test",
    email: "jonaDur@pepemail.com",
    birthday: moment().subtract(12, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test3",
    lastname: "test3",
    username: "test3",
    password: "123456test",
    email: "test3@gmail.com",
    birthday: moment().subtract(1, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test4",
    lastname: "test4",
    username: "test4",
    password: "123456test",
    email: "test4@gmail.com",
    birthday: moment().subtract(9, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test5",
    lastname: "test5",
    username: "test5",
    password: "123456test",
    email: "test5@gmail.com",
    birthday: moment().subtract(2, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test6",
    lastname: "test6",
    username: "test6",
    password: "123456test",
    email: "test6@gmail.com",
    birthday: moment().subtract(3, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test7",
    lastname: "test7",
    username: "test7",
    password: "123456test",
    email: "test7@gmail.com",
    birthday: moment().subtract(5, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test8",
    lastname: "test8",
    username: "test8",
    password: "123456test",
    email: "test8@gmail.com",
    birthday: moment().subtract(8, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test9",
    lastname: "test9",
    username: "test9",
    password: "123456test",
    email: "test9@gmail.com",
    birthday: moment().subtract(11, "year"),
    role: "admin",
    skills: [],
  },
  {
    id: Guid.newGuid(),
    firstname: "test10",
    lastname: "test10",
    username: "test10",
    password: "123456test",
    email: "test10@gmail.com",
    birthday: moment().subtract(15, "year"),
    role: "admin",
    skills: [],
  },
];
